import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { PluginInfo } from '../plugin-discovery.js';

export function generateElectronGlue(electronDir: string, plugin: PluginInfo): string[] {
  const glueDir = join(electronDir, 'src', 'plugin-glue');
  mkdirSync(glueDir, { recursive: true });
  const files: string[] = [];

  const bridgePath = join(glueDir, 'mcp-bridge.ts');
  writeFileSync(bridgePath, generateBridge(plugin), 'utf-8');
  files.push('src/plugin-glue/mcp-bridge.ts');

  const drivePath = join(glueDir, 'drive-client.ts');
  writeFileSync(drivePath, generateDriveClient(plugin), 'utf-8');
  files.push('src/plugin-glue/drive-client.ts');

  return files;
}

function generateDriveClient(plugin: PluginInfo): string {
  return `/**
 * Plugin Glue (click-to-drive): ${plugin.name}
 * Auto-generated by fragment connect — do not edit manually.
 *
 * Lets plugin panels advance the agent session with a click. Any element with a
 * data-drive attribute (a JSON DriveIntent) drives the embedded agent via the
 * app:drive IPC — the SAME path a typed message takes. content must be a
 * fully-formed instruction.
 */

/** Programmatic drive from plugin code. */
export function drive(intent: { model?: string; content: string }): void {
  (window as unknown as { api?: { drive?: (i: unknown) => void } }).api?.drive?.({ source: '${plugin.name}', ...intent });
}

/** Delegated [data-drive] click listener; call once from renderer.tsx after mount. */
export function registerDriveClicks(): void {
  document.addEventListener('click', (e) => {
    const el = (e.target as HTMLElement)?.closest?.('[data-drive]') as HTMLElement | null;
    if (!el) return;
    try {
      const intent = JSON.parse(el.dataset.drive || '{}');
      if (intent.content) drive(intent);
    } catch {
      /* ignore malformed data-drive */
    }
  });
}
`;
}

function generateBridge(plugin: PluginInfo): string {
  const serverNames = Object.keys(plugin.mcpServers);
  const serverImports = serverNames
    .map((name) => {
      const config = plugin.mcpServers[name];
      return `  ${name}: { command: '${config.command}', args: ${JSON.stringify(config.args)} }`;
    })
    .join(',\n');

  return `/**
 * Plugin Glue: ${plugin.name}
 * Auto-generated by fragment connect — do not edit manually.
 *
 * Bridges MCP servers into the Electron main process.
 * Registers IPC handlers and wires tool calls into the timeline.
 */

import { ipcMain } from 'electron';
import type { ToolCall } from '../../../packages/core/src/shared/types.js';

interface McpServer {
  command: string;
  args: string[];
}

const MCP_SERVERS: Record<string, McpServer> = {
${serverImports}
};

let toolCallIdCounter = 0;

/**
 * Register IPC handlers for all MCP servers from ${plugin.name}.
 * Call this from main.ts during app initialization.
 */
export function registerPluginHandlers(
  pushState: () => void,
  addTimelineEntry: (entry: ToolCall) => void,
): void {
${serverNames
  .map(
    (name) => `
  // MCP Server: ${name}
  ipcMain.handle('mcp:${name}', async (_event, toolName: string, args: unknown) => {
    const entry: ToolCall = {
      id: \`mcp-\${++toolCallIdCounter}\`,
      model: 'claude',
      tool: \`${name}.\${toolName}\`,
      target: typeof args === 'string' ? args : JSON.stringify(args).slice(0, 100),
      timestamp: new Date().toISOString(),
      status: 'running',
    };
    addTimelineEntry(entry);
    pushState();

    try {
      entry.status = 'complete';
      pushState();
      return { status: 'ok' };
    } catch (error) {
      entry.status = 'error';
      entry.output = error instanceof Error ? error.message : String(error);
      pushState();
      return { status: 'error', error: entry.output };
    }
  });`,
  )
  .join('\n')}
}

export function getPluginMcpServers(): string[] {
  return ${JSON.stringify(serverNames)};
}
`;
}
