import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { PluginInfo } from '../plugin-discovery.js';

export function generateMobileGlue(mobileDir: string, plugin: PluginInfo): string[] {
  const glueDir = join(mobileDir, 'src', 'plugin-glue');
  mkdirSync(glueDir, { recursive: true });
  const files: string[] = [];

  const drivePath = join(glueDir, 'drive-client.ts');
  writeFileSync(drivePath, generateDriveClient(plugin), 'utf-8');
  files.push('src/plugin-glue/drive-client.ts');

  return files;
}

function generateDriveClient(plugin: PluginInfo): string {
  return `/**
 * Plugin Glue (click-to-drive): ${plugin.name}
 * Auto-generated by fragment connect — do not edit manually.
 *
 * React Native has no DOM data-* attribute — pass a DriveIntent to a Pressable's
 * onPress and call drive(). Advances the agent via ChatService.drive over the
 * WebSocket transport (the app's host runs the agent). content must be a
 * fully-formed instruction.
 */
import { chatService } from '../../../../packages/ui/src/services/grpc-client.js';

export function drive(intent: { model?: string; content: string }): void {
  void chatService.driveIntent({ source: '${plugin.name}', ...intent });
}
`;
}
