import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { PluginInfo } from '../plugin-discovery.js';

export function generateTuiGlue(tuiDir: string, plugin: PluginInfo): string[] {
  const glueDir = join(tuiDir, 'plugin-glue');
  mkdirSync(glueDir, { recursive: true });
  const files: string[] = [];

  for (const serverName of Object.keys(plugin.mcpServers)) {
    const fileName = `plugin_${serverName}.go`;
    const filePath = join(glueDir, fileName);
    writeFileSync(filePath, generatePluginTab(serverName, plugin), 'utf-8');
    files.push(`plugin-glue/${fileName}`);
  }

  return files;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function generatePluginTab(serverName: string, plugin: PluginInfo): string {
  const structName = `${capitalize(serverName)}Plugin`;

  return `// Plugin Glue: ${serverName} from ${plugin.name}
// Auto-generated by fragment connect — do not edit manually.

package pluginglue

import (
\ttea "github.com/charmbracelet/bubbletea"
\t"github.com/charmbracelet/lipgloss"
)

// ${structName} is a TUI tab plugin for the ${serverName} MCP server.
type ${structName} struct {
\tfocused bool
}

func New${structName}() *${structName} {
\treturn &${structName}{}
}

func (p *${structName}) ID() string        { return "${serverName}" }
func (p *${structName}) Name() string      { return "${capitalize(serverName)}" }
func (p *${structName}) Icon() string      { return "◉" }
func (p *${structName}) IsFocused() bool   { return p.focused }
func (p *${structName}) SetFocused(f bool) { p.focused = f }

func (p *${structName}) Init(ctx interface{}) error { return nil }
func (p *${structName}) Start() tea.Cmd             { return nil }
func (p *${structName}) Stop()                      {}

func (p *${structName}) Update(msg tea.Msg) (*${structName}, tea.Cmd) {
\treturn p, nil
}

func (p *${structName}) View(width, height int) string {
\ttitle := lipgloss.NewStyle().
\t\tForeground(lipgloss.Color("#ff8c32")).
\t\tBold(true).
\t\tRender("${capitalize(serverName)} MCP Server")

\tdesc := lipgloss.NewStyle().
\t\tForeground(lipgloss.Color("#555")).
\t\tRender("Connected to ${plugin.name} plugin\\nServer: ${serverName}")

\treturn lipgloss.NewStyle().
\t\tWidth(width).
\t\tHeight(height).
\t\tPadding(1, 2).
\t\tRender(title + "\\n\\n" + desc)
}

func (p *${structName}) KeyHints() []struct{ Key, Help string } {
\treturn []struct{ Key, Help string }{
\t\t{Key: "r", Help: "refresh"},
\t}
}
`;
}
