import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { PluginInfo } from '../plugin-discovery.js';

export function generateVSCodeGlue(vscodeDir: string, plugin: PluginInfo): string[] {
  const glueDir = join(vscodeDir, 'src', 'plugin-glue');
  mkdirSync(glueDir, { recursive: true });
  const files: string[] = [];

  const commandsPath = join(glueDir, 'mcp-commands.ts');
  writeFileSync(commandsPath, generateCommands(plugin), 'utf-8');
  files.push('src/plugin-glue/mcp-commands.ts');

  const drivePath = join(glueDir, 'drive-client.ts');
  writeFileSync(drivePath, generateDriveClient(plugin), 'utf-8');
  files.push('src/plugin-glue/drive-client.ts');

  return files;
}

function generateDriveClient(plugin: PluginInfo): string {
  return `/**
 * Plugin Glue (click-to-drive): ${plugin.name}
 * Auto-generated by fragment connect — do not edit manually.
 *
 * Webview helper: lets plugin panels advance the agent session with a click,
 * via ChatService.drive over the shared transport — the SAME path a typed
 * message takes. content must be a fully-formed instruction.
 */
import { chatService } from '../../../packages/ui/src/services/grpc-client.js';

export function drive(intent: { model?: string; content: string }): void {
  void chatService.driveIntent({ source: '${plugin.name}', ...intent });
}

/** Delegated [data-drive] click listener; call once after the webview mounts. */
export function registerDriveClicks(): void {
  document.addEventListener('click', (e) => {
    const el = (e.target as HTMLElement)?.closest?.('[data-drive]') as HTMLElement | null;
    if (!el) return;
    try {
      const intent = JSON.parse(el.dataset.drive || '{}');
      if (intent.content) drive(intent);
    } catch {
      /* ignore malformed data-drive */
    }
  });
}
`;
}

function generateCommands(plugin: PluginInfo): string {
  const serverNames = Object.keys(plugin.mcpServers);

  return `/**
 * Plugin Glue: ${plugin.name}
 * Auto-generated by fragment connect — do not edit manually.
 *
 * Registers VS Code commands for MCP servers from ${plugin.name}.
 * Wires tool calls into the timeline panel.
 */

import * as vscode from 'vscode';
import type { ToolCall } from '../../../packages/core/src/shared/types.js';

let toolCallIdCounter = 0;

/**
 * Register commands for all MCP servers from ${plugin.name}.
 * Call this from extension.ts activate().
 */
export function registerPluginCommands(
  context: vscode.ExtensionContext,
  controller: { getState: () => any; emit: (event: string, data: any) => void },
): void {
  // click-to-drive: a native VS Code command so tree items / CodeLens / status-bar
  // buttons can advance the agent session (webviews use drive-client.ts instead).
  context.subscriptions.push(
    vscode.commands.registerCommand('${plugin.name}.drive', (intent: { model?: string; content: string }) => {
      const state = controller.getState();
      controller.emit('chat-message', { model: intent.model ?? state.chat.activeModel, content: intent.content });
    }),
  );
${serverNames
  .map(
    (name) => `
  // MCP Server: ${name}
  context.subscriptions.push(
    vscode.commands.registerCommand('${plugin.name}.mcp.${name}', async (toolName: string, args: unknown) => {
      const state = controller.getState();
      const entry: ToolCall = {
        id: \`mcp-\${++toolCallIdCounter}\`,
        model: 'claude',
        tool: \`${name}.\${toolName}\`,
        target: typeof args === 'string' ? args : JSON.stringify(args).slice(0, 100),
        timestamp: new Date().toISOString(),
        status: 'running',
      };
      state.timeline.entries.push(entry);
      controller.emit('state-changed', state);

      try {
        entry.status = 'complete';
        controller.emit('state-changed', state);
      } catch (error) {
        entry.status = 'error';
        entry.output = error instanceof Error ? error.message : String(error);
        controller.emit('state-changed', state);
      }
    }),
  );`,
  )
  .join('\n')}
}

export function getPluginMcpServers(): string[] {
  return ${JSON.stringify(serverNames)};
}
`;
}
