import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { PluginInfo } from '../plugin-discovery.js';

export function generateVSCodeGlue(vscodeDir: string, plugin: PluginInfo): string[] {
  const glueDir = join(vscodeDir, 'src', 'plugin-glue');
  mkdirSync(glueDir, { recursive: true });
  const files: string[] = [];

  const commandsPath = join(glueDir, 'mcp-commands.ts');
  writeFileSync(commandsPath, generateCommands(plugin), 'utf-8');
  files.push('src/plugin-glue/mcp-commands.ts');

  return files;
}

function generateCommands(plugin: PluginInfo): string {
  const serverNames = Object.keys(plugin.mcpServers);

  return `/**
 * Plugin Glue: ${plugin.name}
 * Auto-generated by fragment connect — do not edit manually.
 *
 * Registers VS Code commands for MCP servers from ${plugin.name}.
 * Wires tool calls into the timeline panel.
 */

import * as vscode from 'vscode';
import type { ToolCall } from '../../../packages/core/src/shared/types.js';

let toolCallIdCounter = 0;

/**
 * Register commands for all MCP servers from ${plugin.name}.
 * Call this from extension.ts activate().
 */
export function registerPluginCommands(
  context: vscode.ExtensionContext,
  controller: { getState: () => any; emit: (event: string, data: any) => void },
): void {
${serverNames
  .map(
    (name) => `
  // MCP Server: ${name}
  context.subscriptions.push(
    vscode.commands.registerCommand('${plugin.name}.mcp.${name}', async (toolName: string, args: unknown) => {
      const state = controller.getState();
      const entry: ToolCall = {
        id: \`mcp-\${++toolCallIdCounter}\`,
        model: 'claude',
        tool: \`${name}.\${toolName}\`,
        target: typeof args === 'string' ? args : JSON.stringify(args).slice(0, 100),
        timestamp: new Date().toISOString(),
        status: 'running',
      };
      state.timeline.entries.push(entry);
      controller.emit('state-changed', state);

      try {
        entry.status = 'complete';
        controller.emit('state-changed', state);
      } catch (error) {
        entry.status = 'error';
        entry.output = error instanceof Error ? error.message : String(error);
        controller.emit('state-changed', state);
      }
    }),
  );`,
  )
  .join('\n')}
}

export function getPluginMcpServers(): string[] {
  return ${JSON.stringify(serverNames)};
}
`;
}
